<a href="https://colab.research.google.com/github/AnshulSharma2004/MachineLearning/blob/main/ImbalanceData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
import os
import json
from zipfile import  ZipFile
import random
np.random.seed(0)

In [3]:
kaggle_cred = json.load(open("kaggle.json"))
os.environ['KAGGLE_USERNAME'] = kaggle_cred['username']
os.environ['KAGGLE_KEY'] = kaggle_cred['key']
!kaggle datasets download -d mlg-ulb/creditcardfraud

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
 67% 44.0M/66.0M [00:00<00:00, 165MB/s] 
100% 66.0M/66.0M [00:00<00:00, 168MB/s]


In [4]:
!ls

creditcardfraud.zip  kaggle.json  sample_data


In [5]:
with ZipFile('creditcardfraud.zip', 'r') as zip:
  zip.extractall()

In [6]:
ls

creditcard.csv  creditcardfraud.zip  kaggle.json  sample_data/


In [7]:
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [8]:
df.shape

(284807, 31)

In [10]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [19]:
# clearlly this is imbalance class distribution

std_scaler = StandardScaler()
df['Amount'] = std_scaler.fit_transform(df['Amount'].values.reshape(-1,1))

In [21]:
df.drop('Time', axis=1, inplace=True)

In [22]:
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28    Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  0.244964      0  
1  0.167170  0.125895 -0.008983  0.014724 -0.342475      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  1.160686      0  
3  0.647376 -0.221929  0.062723  0.061458  0.140534      0  
4 -0.206010  0.502292  0.219422  0.215153 -0.073403      0  

[5 rows x 30 columns]

In [23]:
X, y = df.drop('Class', axis=1), df['Class']

In [24]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

#Now train the model with imbalance class distribution

In [38]:
sum(y_test == 1)

147

In [34]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
pred = lr.predict(x_test)
# print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))
print(accuracy_score(y_test, pred))

[[85284    12]
 [   56    91]]
0.999204147794436


In [28]:
# Accuracy is 100% but recall of minority class is low
# we will balance this data set

## Using Smote
### it is a oversampling technique that enchance the minority class by randomly generating data points in minority class

In [30]:
print("Before Oversampling, count of label '1': {}".format(sum(y_train == 1)) )
print("Before Oversampling, count of label '0': {}".format(sum(y_train == 0)) )

Before Oversampling, count of label '1': 345
Before Oversampling, count of label '0': 199019


### We have to do oversampling on the training data not on the overall data
### Beacause during the prediction , we will predict on the original data not on the synthetically generated data

In [31]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=0)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)

In [32]:
print("After Oversampling, count of label '1': {}".format(sum(y_train_smote == 1)) )
print("After Oversampling, count of label '0': {}".format(sum(y_train_smote == 0)) )

After Oversampling, count of label '1': 199019
After Oversampling, count of label '0': 199019


In [33]:
lr1 = LogisticRegression()
lr1.fit(x_train_smote, y_train_smote)
pred1 = lr1.predict(x_test)
print(classification_report(y_test, pred1))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     85296
           1       0.06      0.92      0.11       147

    accuracy                           0.98     85443
   macro avg       0.53      0.95      0.55     85443
weighted avg       1.00      0.98      0.99     85443



In [39]:
print(confusion_matrix(y_test, pred1))
print(accuracy_score(y_test, pred1))

[[83195  2101]
 [   12   135]]
0.975270063082991


## Using NearMiss Algo
### this is undersampling technique in which majority class samples dropout from dataset so that majority class will become equal to minority class and become a class balance betweem them

In [40]:
print("Before Undersampling, counts of label '1': {}".format(sum(y_train == 1)))
print("Before Undersampling, counts of label '0': {} \n".format(sum(y_train == 0)))

Before Undersampling, counts of label '1': 345
Before Undersampling, counts of label '0': 199019 



In [41]:
from imblearn.under_sampling import NearMiss
nm = NearMiss()
x_train_nm, y_train_nm = nm.fit_resample(x_train, y_train)

In [43]:
print("After Undersampling, counts of label '1': {}".format(sum(y_train_nm == 1)))
print("After Undersampling, counts of label '0': {} \n".format(sum(y_train_nm == 0)))

After Undersampling, counts of label '1': 345
After Undersampling, counts of label '0': 345 



In [44]:
lr2 = LogisticRegression()
lr2.fit(x_train_nm, y_train_nm)
pred2 = lr2.predict(x_test)
print(classification_report(y_test, pred2))
print(confusion_matrix(y_test, pred2))
print(accuracy_score(y_test, pred2))

              precision    recall  f1-score   support

           0       1.00      0.55      0.71     85296
           1       0.00      0.95      0.01       147

    accuracy                           0.56     85443
   macro avg       0.50      0.75      0.36     85443
weighted avg       1.00      0.56      0.71     85443

[[47304 37992]
 [    7   140]]
0.5552707653055253


in these two model the model using smote algo is best model for classification beacause accuracy is good also recall for majority and minority class is very good as compare to all other models.