In [19]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import sklearn as sk
print(sk.__version__)

1.3.0


In [2]:
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target
print(X.shape, y.shape)

(150, 4) (150,)


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=100)

In [10]:
rf_clf = RandomForestClassifier(n_estimators=100, bootstrap=True)

In [11]:
# train the Random forest model
rf_clf.fit(X_train, y_train)

RandomForestClassifier()

In [12]:
# Evaluate the model
y_pred_rf = rf_clf.predict(X_test)
y_pred_rf

array([2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 2, 2,
       0])

In [13]:
print(f'accuracy of model:',accuracy_score(y_test, y_pred_rf))

accuracy of model: 0.9555555555555556


In [14]:
print(confusion_matrix(y_test, y_pred_rf))

[[16  0  0]
 [ 0 10  1]
 [ 0  1 17]]


In [15]:
# Feature Importance Score
print(dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
print(rf_clf.feature_importances_)

[0.0946316  0.02321728 0.48197763 0.40017349]


## Bagging Classifier

In [31]:
dt_clf = DecisionTreeClassifier() 
# Bagging Classifier
bg_clf = BaggingClassifier(estimator=dt_clf, n_estimators=5, bootstrap=True,max_features=3, oob_score=True, random_state=100 )

In [32]:
bg_clf.fit(X_train, y_train)

c:\Users\saura\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:789: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn(
c:\Users\saura\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:795: RuntimeWarning: invalid value encountered in divide
  oob_decision_function = predictions / predictions.sum(axis=1)[:, np.newaxis]


BaggingClassifier(estimator=DecisionTreeClassifier(), max_features=3,
                  n_estimators=5, oob_score=True, random_state=100)

In [33]:
y_pred_bg = bg_clf.predict(X_test)

In [34]:
print(f'accuracy_score of bagging classifier', accuracy_score(y_test, y_pred_bg))

accuracy_score of bagging classifier 0.9555555555555556


In [35]:
print(bg_clf.oob_score_)

0.8666666666666667


In [36]:
# The Bagging Estimator
print(bg_clf.estimators_)

[DecisionTreeClassifier(random_state=1269732080), DecisionTreeClassifier(random_state=1996346219), DecisionTreeClassifier(random_state=1223433847), DecisionTreeClassifier(random_state=1840964751), DecisionTreeClassifier(random_state=1146906547)]


In [37]:
print(bg_clf.estimators_features_)

[array([2, 1, 3]), array([0, 1, 2]), array([2, 0, 1]), array([0, 1, 2]), array([1, 2, 0])]
